kind: pipeline
name: development-ci
type: docker

steps:
  - name: node-server
    image: simplestakingcom/tezedge:latest
    pull: if-not-exists
    detach: true
    privileged: true

  - name: build #build the frontend docker image
    image: docker:latest
    commands:
      - docker build --no-cache --build-arg branch=${DRONE_BRANCH} -t drone-tezedge-explorer:latest -f Dockerfile .
    volumes:
      - name: docker_sock
        path: /var/run/docker.sock

  - name: frontend-server
    image: drone-tezedge-explorer:latest
    pull: if-not-exists
    detach: true
    privileged: true
    environment:
      SANDBOX: 'https://${DRONE_BRANCH}.dev.tezedge.com:3030'
      API: '[{"id":"drone","name":"drone-test-node","http":"http://node-server:80","monitoring":"http://${DRONE_BRANCH}.dev.tezedge.com:38732/resources/tezedge","debugger":"http://${DRONE_BRANCH}.dev.tezedge.com:17732","ws":"ws://${DRONE_BRANCH}.dev.tezedge.com:4927"}]'
    depends_on:
      - node-server
      - build

  - name: test
    image: cypress/included:6.2.1
    environment:
      CYPRESS_baseUrl: http://frontend-server:80
    depends_on:
      - frontend-server

  - name: publish
    image: plugins/docker
    when:
      branch:
        - develop
    depends_on:
      - test
    settings:
      repo: simplestakingcom/tezedge-explorer
      tags: latest
      dockerfile: Dockerfile
      build_args:
        - branch=develop
        - commit=${DRONE_COMMIT}
      username:
        from_secret: docker_hub_username
      password:
        from_secret: docker_hub_pswd

image_pull_secrets:
  - docker_pull_secret

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock

trigger:
  branch:
    - develop
    - master # same process, without the publish step
  event: push

---

kind: pipeline
name: deployment-ci
type: docker

steps:
- name: build #build the frontend docker image
  image: docker:latest
  commands:
    - docker build --no-cache --build-arg branch=master -t drone-tezedge-explorer:latest -f Dockerfile .
  volumes:
    - name: docker_sock
      path: /var/run/docker.sock

- name: frontend-server #detach it to access it inside test step
  image: drone-tezedge-explorer:latest
  pull: if-not-exists
  detach: true
  privileged: true
  environment:
    SANDBOX: 'https://master.dev.tezedge.com:3030'
    API: '[{"id":"master","name":"master.dev.tezedge","http":"http://master.dev.tezedge.com:18732","monitoring":"http://master.dev.tezedge.com:38732/resources/tezedge","debugger":"http://master.dev.tezedge.com:17732","ws":false}]'
  depends_on:
    - build

- name: test
  image: cypress/included:6.2.1
  environment:
    CYPRESS_baseUrl: http://frontend-server:80
  depends_on:
    - frontend-server

- name: publish
  image: plugins/docker
  depends_on:
    - test
  settings:
    repo: simplestakingcom/tezedge-explorer
    tags:
      - ${DRONE_TAG}
      - latest-release
    dockerfile: Dockerfile
    build_args:
      - branch=master
      - commit=${DRONE_COMMIT}
    username:
      from_secret: docker_hub_username
    password:
      from_secret: docker_hub_pswd

- name: cp-static
  image: drone-tezedge-explorer:latest
  depends_on:
    - test
  privileged: true
  pull: if-not-exists
  volumes:
    - name: static_page
      path: /etc/static_page
  commands:
    - cp -R /usr/share/nginx/html/* /etc/static_page

- name: publish-firebase
  image: devillex/docker-firebase
  pull: if-not-exists
  volumes:
    - name: static_page
      path: /drone/src/dist/tezedge-explorer
  environment:
    FIREBASE_API_TOKEN:
      from_secret: FIREBASE_API_TOKEN
  depends_on:
    - test
    - cp-static
    - publish
  commands:
    - firebase deploy --token=$${FIREBASE_API_TOKEN}

image_pull_secrets:
  - docker_pull_secret

volumes:
  - name: docker_sock
    host:
      path: /var/run/docker.sock
  - name: static_page
    host:
      path: /etc/tezedge-ci/tezedge-explorer/

trigger:
  ref: refs/tags/**
  event: tag
