version: '3'
services:
  tezedge-explorer:
    image: simplestakingcom/tezedge-explorer:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - SANDBOX=https://carthage.tezedge.com:3030
      - DEBUGGER=http://master.dev.tezedge.com:17733
      - API=[{"id":"rust","name":"rust.master.dev.tezedge","http":"http://master.dev.tezedge.com:18733","monitoring":"http://master.dev.tezedge.com:38733/resources/tezedge","ws":"ws://master.dev.tezedge.com:4927","p2p_port":"9732"}]
    hostname: tezedge-explorer
    # network_mode: host
  cypress:
    image: "cypress/included:6.2.1"
    depends_on:
      - tezedge-explorer
    environment:
      - CYPRESS_baseUrl=http://docker.for.mac.localhost:8080
    working_dir: /e2e
    volumes:
    - ./:/e2e
